# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inference_application.code.protocompiled.basic_inference_pb2 as basic__inference__pb2


class BasicInferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.stream_stream(
                '/basic_inference.BasicInferenceService/predict',
                request_serializer=basic__inference__pb2.BasicInferenceRequest.SerializeToString,
                response_deserializer=basic__inference__pb2.BasicInferenceResponse.FromString,
                )


class BasicInferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.stream_stream_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=basic__inference__pb2.BasicInferenceRequest.FromString,
                    response_serializer=basic__inference__pb2.BasicInferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'basic_inference.BasicInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BasicInferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/basic_inference.BasicInferenceService/predict',
            basic__inference__pb2.BasicInferenceRequest.SerializeToString,
            basic__inference__pb2.BasicInferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
