# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import grpc.experimental
from inference_application.code.protocompiled import extended_inference_pb2 as inference__application_dot_code_dot_proto_dot_extended__inference__pb2


class ExtendedInferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.stream_stream(
                '/extended_inference.ExtendedInferenceService/predict',
                request_serializer=inference__application_dot_code_dot_proto_dot_extended__inference__pb2.ExtendedInferenceRequest.SerializeToString,
                response_deserializer=inference__application_dot_code_dot_proto_dot_extended__inference__pb2.ExtendedInferenceResponse.FromString,
                )


class ExtendedInferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtendedInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.stream_stream_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=inference__application_dot_code_dot_proto_dot_extended__inference__pb2.ExtendedInferenceRequest.FromString,
                    response_serializer=inference__application_dot_code_dot_proto_dot_extended__inference__pb2.ExtendedInferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'extended_inference.ExtendedInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExtendedInferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/extended_inference.ExtendedInferenceService/predict',
            inference__application_dot_code_dot_proto_dot_extended__inference__pb2.ExtendedInferenceRequest.SerializeToString,
            inference__application_dot_code_dot_proto_dot_extended__inference__pb2.ExtendedInferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
