# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference-setup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inference-setup.proto\x12\x0f\x62\x61sic_inference\x1a\x1cgoogle/protobuf/struct.proto\"\xac\x01\n\x14TransformationParams\x12\n\n\x02id\x18\x01 \x01(\t\x12\x41\n\x06params\x18\x02 \x03(\x0b\x32\x31.basic_inference.TransformationParams.ParamsEntry\x1a\x45\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"{\n\x0eInferenceSetup\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12>\n\x0ftransformations\x18\x03 \x03(\x0b\x32%.basic_inference.TransformationParams\"9\n\x16InferenceSetupResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2j\n\x13\x42\x61sicInferenceSetup\x12S\n\x05setup\x12\x1f.basic_inference.InferenceSetup\x1a\'.basic_inference.InferenceSetupResponse\"\x00\x62\x06proto3')



_TRANSFORMATIONPARAMS = DESCRIPTOR.message_types_by_name['TransformationParams']
_TRANSFORMATIONPARAMS_PARAMSENTRY = _TRANSFORMATIONPARAMS.nested_types_by_name['ParamsEntry']
_INFERENCESETUP = DESCRIPTOR.message_types_by_name['InferenceSetup']
_INFERENCESETUPRESPONSE = DESCRIPTOR.message_types_by_name['InferenceSetupResponse']
TransformationParams = _reflection.GeneratedProtocolMessageType('TransformationParams', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRANSFORMATIONPARAMS_PARAMSENTRY,
    '__module__' : 'inference_setup_pb2'
    # @@protoc_insertion_point(class_scope:basic_inference.TransformationParams.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _TRANSFORMATIONPARAMS,
  '__module__' : 'inference_setup_pb2'
  # @@protoc_insertion_point(class_scope:basic_inference.TransformationParams)
  })
_sym_db.RegisterMessage(TransformationParams)
_sym_db.RegisterMessage(TransformationParams.ParamsEntry)

InferenceSetup = _reflection.GeneratedProtocolMessageType('InferenceSetup', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCESETUP,
  '__module__' : 'inference_setup_pb2'
  # @@protoc_insertion_point(class_scope:basic_inference.InferenceSetup)
  })
_sym_db.RegisterMessage(InferenceSetup)

InferenceSetupResponse = _reflection.GeneratedProtocolMessageType('InferenceSetupResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCESETUPRESPONSE,
  '__module__' : 'inference_setup_pb2'
  # @@protoc_insertion_point(class_scope:basic_inference.InferenceSetupResponse)
  })
_sym_db.RegisterMessage(InferenceSetupResponse)

_BASICINFERENCESETUP = DESCRIPTOR.services_by_name['BasicInferenceSetup']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFORMATIONPARAMS_PARAMSENTRY._options = None
  _TRANSFORMATIONPARAMS_PARAMSENTRY._serialized_options = b'8\001'
  _TRANSFORMATIONPARAMS._serialized_start=73
  _TRANSFORMATIONPARAMS._serialized_end=245
  _TRANSFORMATIONPARAMS_PARAMSENTRY._serialized_start=176
  _TRANSFORMATIONPARAMS_PARAMSENTRY._serialized_end=245
  _INFERENCESETUP._serialized_start=247
  _INFERENCESETUP._serialized_end=370
  _INFERENCESETUPRESPONSE._serialized_start=372
  _INFERENCESETUPRESPONSE._serialized_end=429
  _BASICINFERENCESETUP._serialized_start=431
  _BASICINFERENCESETUP._serialized_end=537
# @@protoc_insertion_point(module_scope)
