include:
  - project: 'sripas/gitlab-ci-templates'
    file: 'mirror-repo.gitlab-ci.yml'
  - project: 'sripas/gitlab-ci-templates'
    file: 'mirror-wiki.gitlab-ci.yml'
  - project: 'sripas/gitlab-ci-templates'
    file: 'publish-docs.gitlab-ci.yml'
