version: '3'
services:
  local_operations:
    restart: always
    container_name: local_operations
    build: application
    networks:
      - default
    ports:
      - "9050:9050"
    depends_on:
      - db
  db:
    container_name: db
    restart: always
    image: mongo:latest
    networks:
      - default

networks:
  default:
    driver: bridge
    name: custom_fl