version: '3'
services:
  inference:
    restart: always
    image: karola766/inferenceapp:latest
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      - REPOSITORY_ADDRESS=http://flrepository:9012
    networks:
      - default
    ports:
      - "50051:50051"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
    name: custom_fl