version: '3.8'
services:
  local_operations:
    restart: always
    image: karola766/trainingapp:latest
    build:
      context: application
      dockerfile: Dockerfile
    environment:
      - USER_INDEX=${USER_INDEX}
    networks:
      - default
    ports:
      - "905${USER_INDEX}:9050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ${FL_LOCAL_OP_DATA_FOLDER}
        target: /data
      - type: bind
        source: ./preprocessed
        target: /preprocessed
  db:
    container_name: "db-${USER_INDEX}"
    build:
      context: db
      dockerfile: "Dockerfile.db"
    restart: always
    image: karola766/localdb:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
  inferenceapp:
    image: karola766/inferenceapp:latest
    restart: always
    build:
      context: inference_application
      dockerfile: "Dockerfile.inf"
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
    name: custom_fl
