version: '3.8'
services:
  app:
    container_name: local_operations
    build: application
    ports:
      - "9050:9050"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"