version: '3.8'
services:
  local_operations:
    restart: always
    build:
      context: application
      dockerfile: Dockerfile
    environment:
      - USER_INDEX=${USER_INDEX}
    networks:
      - default
    ports:
      - "905${USER_INDEX}:9050"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./data
        target: /data
  db:
    container_name: "db-${USER_INDEX}"
    restart: always
    image: mongo:latest
    networks:
      - default

networks:
  default:
    driver: bridge
    name: custom_fl
