version: '3'
services:
  inferenceapp:
    image: assistiot/fl_local_operations_inference:latest
    restart: always
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      - REPOSITORY_ADDRESS=http://flrepository:9012
    networks:
      - default
    ports:
      - "50052:50051"
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

