version: '3.8'
services:
  app:
    container_name: local_operations
    build: application
    ports:
      - "9050:9050"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
# Paths to volumes should be absolute and will be different on non-Windows machines
    volumes:
      - c:/data/db:/data/db
      - c:/data/configdb:/data/configdb