version: '3'
services:
  local_operations:
    env_file:
      - application/.env
    restart: always
    build: application
    networks:
      - default
    ports:
      - "905${USER_INDEX}:9050"
    depends_on:
      - db
  db:
    container_name: "db-${USER_INDEX}"
    restart: always
    image: mongo:latest
    networks:
      - default

networks:
  default:
    driver: bridge
    name: custom_fl