kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-data-lo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: local-data-claim
    namespace: default
  hostPath:
    path: "/home/karokaro/assist-repositories/fl-local-operations/data"