kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-data-lo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: local-data-claim
  hostPath:
    path: "data"