kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-data-lo
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wasielk/federated-experiments/fl-local-operations/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path