kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fllocalops-config-map-{{ include "inferenceapp.fullname" . }}
data:
  # Configuration values can be set as key-value properties
  HOST: "0.0.0.0"
  PORT: "9050"
  DB_PORT: "27017"
  DATA_FORMAT_FILE: "format.json"
  DATA_PIPELINE_FILE: "transformation_pipeline.json"
  DATA_FOLDER: "/data"
  PREPROCESSED_FOLDER: "/preprocessed"
  REPOSITORY_ADDRESS: "http://flrepositorylocaldb2-flrepositorydb-flrepository.default.svc.cluster.local:9012"