apiVersion: v1
kind: ConfigMap
metadata:
  name: fltraining-config-map-{{ include "trainingapp.fullname" . }}
data:
  format.json: |
    {"x":{"data_types":{
    "image": {
        "size": [32,32,3],
        "normalized": false
    }}},
    "y":{"data_types":{
    "numerical": {
        "size": [1],
        "normalized": false
    } }}}
  model.json: |
    {"x":
    {"data_types":{
    "image": {
        "size": [32,32,3]
    }   
    }
    }, 
    "y": {"data_types":{
      "categorical": {
        "size": [10]
    }   
    }
    }
    }
  transformation_pipeline_train.json: |
    [
        {
        "id": "application.tests.categorical_transformation",
        "parameters": {
            "categories":10
        }
        }
    ]
  transformation_pipeline_test.json: |
    [
        {
            "id": "application.tests.categorical_transformation",
            "parameters": {
                "categories":10
            }
        }
    ]
  setup.json: |
    {
    "data_loader": "application.tests.new_loader",
    "client_library": {
            "keras":{
                "id": "application.tests.new_keras_client"
            },
            "pytorch": {
                "id": ""
            }
        }
    }