kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-data-lo-{{ include "trainingapp.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: local-data-claim-{{ include "trainingapp.fullname" . }}
    namespace: default
  hostPath:
    path: "/local-operations/data"