{{- if .Values.inferenceapp.fullDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trainingapp.fullname" . }}-svc2
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "trainingapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.trainingapp.service2.type }}
  ports:
    - port: {{ .Values.trainingapp.service2.port }}
      targetPort: {{ .Values.trainingapp.service2.targetPort }}
      protocol: {{ .Values.trainingapp.service2.protocol }}
      {{- if and (or (eq .Values.trainingapp.service2.type "NodePort") (eq .Values.trainingapp.service2.type "LoadBalancer")) (not (empty .Values.trainingapp.service2.nodePort)) }}
      nodePort: {{ .Values.trainingapp.service2.nodePort }}
      {{ end }}
  selector:
    {{- include "trainingapp.selectorLabels" . | nindent 4 }}
{{- end}}