
# Default values for enabler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override enabler.fullname template (will maintain the release name)
nameOverride: ""
# String to fully override enabler.fullname template
fullnameOverride: ""
# Deploy all the components in the same node
enablerNodeSelector: {}
# Component inferenceapp values
inferenceapp:
  tier: internal
  custom_setup: False
  image:
    repository: assistiot/fl_local_operations_inference
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  replicaCount: 1
  service:
    type: NodePort
    nodePort: ""
    port: 50051
    targetPort: 50051
    containerPort: 50051
    protocol: TCP
  metrics:
    type: NodePort
    nodePort: ""
    port: 9000
    targetPort: 9000
    containerPort: 9000
    protocol: TCP
  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  fullDeployment:
    enabled: true

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.


  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component trainingapp values
trainingapp:
  tier: external
  custom_setup: False
  image:
    repository: assistiot/fl_local_operations
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  replicaCount: 1
  service:
    type: NodePort
    nodePort: ""
    port: 9050
    targetPort: 9050
    containerPort: 9050
    protocol: TCP

  service2:
    type: NodePort
    nodePort: ""
    port: 80
    targetPort: 8080
    containerPort: 8080

  ws:
    type: NodePort
    nodePort: ""
    port: 30080
    targetPort: 80
    containerPort: 80

  metrics:
    type: NodePort
    nodePort: ""
    port: 9000
    targetPort: 9000
    containerPort: 9000
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.

  persistence:
    mountPath: /data
    accessModes:
      - ReadWriteOnce
    size: 3Gi

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}



# Component db values
db:
  tier: internal
  image:
    repository: assistiot/fl_repository_db
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  replicaCount: 1
  service:
    type: NodePort
    nodePort: ""
    port: 27017
    targetPort: 27017
    containerPort: 27017
    protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # Include here the environment variables to be used in the component's manifest (container section).
  # Here and in the manifest is included an example.
  envVars:
    exampleEnvVar: exampleValue

  persistence:
    mountPath: /bitnami/mongodb
    accessModes:
      - ReadWriteOnce
    size: 50Mi

  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

