apiVersion: v1
kind: ConfigMap
metadata:
  name: flinference-config-map-{{ include "inferenceapp.fullname" . }}
data:
  format.json: |
    {
        "data_types":{
            "numerical":{
                "size": [5,4],
                "normalized": false
            }   
        }
    }
  model.json: |
    {
    "model_name": "fall-detection",
    "model_version": "pilot-2-1",
    "library": "tflite",
    "input_format":{
        "data_types":{
            "numerical": {
                "size": [1,5,4],
                "normalized": true
                }   
            }
        }
    }
  transformation_pipeline.json: |
    [
    {
        "id": "inference_application.custom.basic_norm",
        "parameters": {

        }
    },
    {
        "id": "inference_application.custom.expansion",
        "parameters": {
            "axis": 0

        }
    }
    ]
  setup.json: |
    {
    "service": {
        "modules":["inference_application.code.protocompiled.basic_inference_pb2", "inference_application.code.protocompiled.basic_inference_pb2_grpc", "inference_application.code.services.basic_inference_svc"],
        "method":"basic-inf-method-protocompiled",
        "servicer": "basic-inf-svc"
      },
    "inference":{
        "inferencer": "inference_application.code.inferencers.tflite_inferencer"
      }
    }