{{- if .Values.inferenceapp.fullDeployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trainingapp.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "trainingapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.trainingapp.service.type }}
  ports:
    - name: main
      port: {{ .Values.trainingapp.service.port }}
      targetPort: {{ .Values.trainingapp.service.targetPort }}
      protocol: {{ .Values.trainingapp.service.protocol }}
      {{- if and (or (eq .Values.trainingapp.service.type "NodePort") (eq .Values.trainingapp.service.type "LoadBalancer")) (not (empty .Values.trainingapp.service.nodePort)) }}
      nodePort: {{ .Values.trainingapp.service.nodePort }}
      {{ end }}
    - name: ws
      port: {{ .Values.trainingapp.ws.port }}
      targetPort: {{ .Values.trainingapp.ws.targetPort }}
      protocol: {{ .Values.trainingapp.ws.protocol }}
      {{- if and (or (eq .Values.trainingapp.ws.type "NodePort") (eq .Values.trainingapp.ws.type "LoadBalancer")) (not (empty .Values.trainingapp.ws.nodePort)) }}
      nodePort: {{ .Values.trainingapp.ws.nodePort }}
      {{ end }}
    - name: metrics
      port: {{ .Values.trainingapp.metrics.port }}
      targetPort: {{ .Values.trainingapp.metrics.targetPort }}
      protocol: {{ .Values.trainingapp.metrics.protocol }}
      {{- if and (or (eq .Values.trainingapp.metrics.type "NodePort") (eq .Values.trainingapp.metrics.type "LoadBalancer")) (not (empty .Values.trainingapp.metrics.nodePort)) }}
      nodePort: {{ .Values.trainingapp.metrics.nodePort }}
      {{ end }}
  selector:
    {{- include "trainingapp.selectorLabels" . | nindent 4 }}
{{- end}}